<a href="https://colab.research.google.com/github/Kim-Ken/my_implement_algo/blob/master/logistic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [223]:
print("aaa")

aaa


In [0]:
import numpy as np
class logisticRegress(object):
  def __init__(self,classNum,featureNum,epoch=100,alpha=0.001):
    self.W = np.random.random((classNum,featureNum+1))
    self.class_label =[0,1,2]
    self.epoch = epoch
    self.alpha = alpha

  def fit(self,X,y):
    for t in range(self.epoch):
      for j,w in enumerate(self.W):
        #if t %100==99:
        #  self.alpha*=0.5
        dw = (self.alpha * self.gd(X,y,w,j))
        #print("w",j)
        #print(dw)
        self.W[j]= w - dw
        
      #print(self.W)
      #if np.linalg.norm(dw,ord=1) < 0.001:
       # break


  def predict(self,x):
    x_p = np.append(np.ones(1),x)
    return self.softmax(x_p)
  
  def gd(self,X,y,w,j):
    dw = 0
    for i,x in enumerate(X):
      if y[i] == self.class_label[j]:
        #print("label:",self.class_label[j],' :j',j," :y[i]",y[i]," :i",i)
        t=1.0
      else:
        t=0.0
      #print(t)
      x_p = np.append(np.ones(1),x)
      #print(x_p)
      dw+=(self.softmax(x_p)[j]-t)*x_p
      #print(dw)
    return dw

  def softmax(self,x):
    ListExp = []
    for w in self.W:
      ax=np.dot(w,x)
      #print(ax)
      ListExp.append(np.exp(ax))
    exps = np.array(ListExp)
    return exps/exps.sum()

In [0]:
from sklearn.datasets import load_iris
iris = load_iris()


In [226]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [0]:
logs = logisticRegress(3,4)

In [0]:
logs.fit(iris.data,iris.target)

In [229]:
print(logs.W)

[[ 1.04770818  1.06385919  1.74497804 -1.11321609 -0.03947895]
 [ 0.24271201  1.07897484  0.4531051   0.55440832 -0.04050169]
 [ 0.30317332 -0.23558503  0.38572038  1.92662683  1.02802488]]


In [230]:
pred_list = []
tf = []
for i,d in enumerate(iris.data):
  l=np.argmax(logs.predict(d))
  if iris.target[i]==l:
    tf.append(1)
  else:
    tf.append(0)
  pred_list.append(l)


print(pred_list)
print(sum(tf)/len(tf))


[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]
0.9733333333333334
